### ISSUE TITLE
能提供一个签名的范例嘛

### ISSUE THREAD

**Issue by s8246809** [coinmex/coinmex-java-api-sdk#1]
我一直显示验证错误，也不知道是哪问题。能提供一个正确的签名范例不，我好知道是不是签名方式错了，也方便修改。

**Comment by Chinchilladale** [comment]
签名字符串：timestamp + method + requestPath + queryString + body
如：1534938006.402GET/api/v1/spot/ccex/account/assets
签名串：VMypXPuEtfrArMuICsgdLn3CWf4Ise/PpRfHQsHSUuk=
另外在 com.coinmex.dax.sdk.openapi.common.utils.SignatureUtils#generate 中有提供签名方法，可以参考一下

**Comment by COINMEX-PETER** [comment]
@s8246809 您使用的是什么语言？

**Comment by COINMEX-PETER** [comment]
@s8246809 方便的话我们可以邮件沟通 我的邮箱是peter@coinmex.com
